/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cartoon_sports_car.gltf --transform
Author: RCC Design (https://sketchfab.com/retrovalorem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cartoon-sports-car-0fd87559642a41b7a7924876ad3e9399
Title: Cartoon Sports Car
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/cartoon_sports_car-transformed.glb'
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="UnityGlTF_root_0">
                <group
                  name="node_CARRERA_-1346_2"
                  rotation={[0, -Math.PI / 2, 0]}
                >
                  <group
                    name="node_left_door_gloss_-1370_4"
                    position={[-0.94, 0.66, -0.74]}
                  >
                    <group name="node_left_door_-1420_19">
                      <group
                        name="node_left_door_glass_-1430_23"
                        position={[0.28, 0.61, 0.69]}
                      >
                        <mesh
                          name="Object_37"
                          geometry={nodes.Object_37.geometry}
                          material={materials.CARRERA_4096_GLASS}
                        />
                      </group>
                      <group
                        name="node_left_mirror_-1432_24"
                        position={[0, 0.37, 0.29]}
                      >
                        <mesh
                          name="Object_39"
                          geometry={nodes.Object_39.geometry}
                          material={materials.CARRERA_4096_MIRRORS}
                        />
                      </group>
                      <mesh
                        name="Object_35"
                        geometry={nodes.Object_35.geometry}
                        material={materials.CARRERA_4096_MATTE}
                      />
                    </group>
                    <mesh
                      name="Object_33"
                      geometry={nodes.Object_33.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group
                    name="node_right_door_gloss_-1368_3"
                    position={[0.94, 0.66, -0.74]}
                  >
                    <group name="node_right_door_-1412_15">
                      <group
                        name="node_right_door_glass_-1468_28"
                        position={[-0.28, 0.61, 0.69]}
                      >
                        <mesh
                          name="Object_53"
                          geometry={nodes.Object_53.geometry}
                          material={materials.CARRERA_4096_GLASS}
                        />
                      </group>
                      <group
                        name="node_right_mirror_-1470_29"
                        position={[0, 0.37, 0.29]}
                      >
                        <mesh
                          name="Object_55"
                          geometry={nodes.Object_55.geometry}
                          material={materials.CARRERA_4096_MIRRORS}
                        />
                      </group>
                      <mesh
                        name="Object_51"
                        geometry={nodes.Object_51.geometry}
                        material={materials.CARRERA_4096_MATTE}
                      />
                    </group>
                    <mesh
                      name="Object_49"
                      geometry={nodes.Object_49.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group name="node_spoiler1_-1406_12">
                    <group name="node_spoiler2_-1422_20">
                      <mesh
                        name="Object_59"
                        geometry={nodes.Object_59.geometry}
                        material={materials.CARRERA_4096_MATTE}
                      />
                    </group>
                    <mesh
                      name="Object_57"
                      geometry={nodes.Object_57.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group
                    name="node_brakes1_-1392_5"
                    position={[-0.85, 0.33, -1.2]}
                  >
                    <group name="node_rim1_-1418_18">
                      <group name="node_tyre1_-1438_25">
                        <mesh
                          name="Object_11"
                          geometry={nodes.Object_11.geometry}
                          material={materials.CARRERA_4096_MATTE}
                        />
                      </group>
                      <mesh
                        name="Object_9"
                        geometry={nodes.Object_9.geometry}
                        material={materials.CARRERA_4096}
                      />
                    </group>
                    <mesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group
                    name="node_brakes2_-1394_6"
                    position={[0.85, 0.33, -1.2]}
                  >
                    <group name="node_rim2_-1410_14">
                      <group name="node_tyre2_-1452_26">
                        <mesh
                          name="Object_17"
                          geometry={nodes.Object_17.geometry}
                          material={materials.CARRERA_4096_MATTE}
                        />
                      </group>
                      <mesh
                        name="Object_15"
                        geometry={nodes.Object_15.geometry}
                        material={materials.CARRERA_4096}
                      />
                    </group>
                    <mesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group
                    name="node_brakes003_-1396_7"
                    position={[0.85, 0.33, 0.83]}
                  >
                    <group name="node_rim003_-1414_16">
                      <group name="node_tyre003_-1456_27">
                        <mesh
                          name="Object_23"
                          geometry={nodes.Object_23.geometry}
                          material={materials.CARRERA_4096_MATTE}
                        />
                      </group>
                      <mesh
                        name="Object_21"
                        geometry={nodes.Object_21.geometry}
                        material={materials.CARRERA_4096}
                      />
                    </group>
                    <mesh
                      name="Object_19"
                      geometry={nodes.Object_19.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group
                    name="node_brakes004_-1398_8"
                    position={[-0.85, 0.33, 0.83]}
                  >
                    <group name="node_rim004_-1416_17">
                      <group name="node_tyre004_-1480_30">
                        <mesh
                          name="Object_29"
                          geometry={nodes.Object_29.geometry}
                          material={materials.CARRERA_4096_MATTE}
                        />
                      </group>
                      <mesh
                        name="Object_27"
                        geometry={nodes.Object_27.geometry}
                        material={materials.CARRERA_4096}
                      />
                    </group>
                    <mesh
                      name="Object_25"
                      geometry={nodes.Object_25.geometry}
                      material={materials.CARRERA_4096}
                    />
                  </group>
                  <group name="node_front_lamps_-1400_9">
                    <mesh
                      name="Object_31"
                      geometry={nodes.Object_31.geometry}
                      material={materials.CARRERA_4096_HEADLIGHTS}
                    />
                  </group>
                  <group name="node_matte1_-1402_10">
                    <group name="node_MIRRORS_-1424_21">
                      <mesh
                        name="Object_43"
                        geometry={nodes.Object_43.geometry}
                        material={materials.CARRERA_4096_MIRRORS}
                      />
                    </group>
                    <group
                      name="node_steering_wheel_-1426_22"
                      position={[-0.31, 0.93, -0.41]}
                      rotation={[-Math.PI / 9, 0, 0]}
                    >
                      <mesh
                        name="Object_45"
                        geometry={nodes.Object_45.geometry}
                        material={materials.CARRERA_4096_MATTE}
                      />
                    </group>
                    <mesh
                      name="Object_41"
                      geometry={nodes.Object_41.geometry}
                      material={materials.CARRERA_4096_MATTE}
                    />
                  </group>
                  <group name="node_rear_lamps_-1404_11">
                    <mesh
                      name="Object_47"
                      geometry={nodes.Object_47.geometry}
                      material={materials.CARRERA_4096_lamps}
                    />
                  </group>
                  <group name="node_windows_-1408_13">
                    <mesh
                      name="Object_61"
                      geometry={nodes.Object_61.geometry}
                      material={materials.CARRERA_4096_GLASS}
                    />
                  </group>
                  <group
                    name="node_BASE_-1006_1"
                    rotation={[Math.PI / 2, 0, 1.69]}
                    scale={0.8}
                  >
                    <mesh
                      name="Object_63"
                      geometry={nodes.Object_63.geometry}
                      material={materials.TARMAC}
                    />
                  </group>
                  <mesh
                    name="Object_5"
                    geometry={nodes.Object_5.geometry}
                    material={materials.CARRERA_4096}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/cartoon_sports_car-transformed.glb');
